Repository AdevintaSpain/Leku, pull requests merged in 2019-02, with the labels that each got.

#218 Project migrated to AndroidX
  .travis.yml
  app/build.gradle
  app/src/main/java/com/schibsted/mappicker/MainActivity.kt
  gradle.properties
  leku/build.gradle
  leku/src/androidTest/java/com/schibsted/leku/LocationPickerActivityShould.kt
  leku/src/androidTest/java/util/OrientationChangeAction.kt
  leku/src/androidTest/java/util/PermissionGranter.kt
  leku/src/main/java/com/schibstedspain/leku/LocationPickerActivity.kt
  leku/src/main/java/com/schibstedspain/leku/permissions/PermissionUtils.kt
  leku/src/main/res/layout-land/leku_activity_location_picker.xml
  leku/src/main/res/layout-normal-v21/leku_activity_location_picker.xml
  leku/src/main/res/layout-normal/leku_activity_location_picker.xml
  leku/src/main/res/layout-xlarge-v21/leku_activity_location_picker.xml
  leku/src/main/res/layout-xlarge/leku_activity_location_picker.xml
  leku/src/main/res/layout/leku_activity_location_picker.xml
  leku/src/main/res/layout/leku_toolbar_search.xml
Labels: ready to merge

#220 Add map style feature
  README.md
  app/src/main/java/com/schibsted/mappicker/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/raw/map_style_retro.json
  app/src/main/res/values/strings.xml
  leku/src/main/java/com/schibstedspain/leku/LocationPickerActivity.kt
Labels: enhancement

#222 Correct artifact generation
  README.md
  build.gradle
  leku/build.gradle
  version.properties
Labels: review

#223 Removed trending badge because is not working any more
  README.md
Labels: ready to merge

#224 Suppress warning magic number
  leku/src/main/java/com/schibstedspain/leku/CountryLocaleRect.kt
Labels: review

#221 Added Hong Kong search zone
  leku/src/main/java/com/schibstedspain/leku/CountryLocaleRect.kt
Labels: ready to merge

#225 New version 6.0.0
  README.md
  app/build.gradle
  app/src/main/res/values/strings.xml
  leku/build.gradle
  version.properties
Labels: ready to merge

#228 Added Brazil country locale rect
  leku/src/main/java/com/schibstedspain/leku/CountryLocaleRect.kt
Labels: review
